version: "3.9"

services:
    smarteval:
        build: api/
        stdin_open: true
        tty: true
        working_dir: /smarteval
        ports:
            - 3030:3030
        networks:
            - backend
        volumes:
            - type: bind
              source: ./api/db
              target: /smarteval/db
            - type: bind
              source: ./api/middleware
              target: /smarteval/middleware
            - type: bind
              source: ./api/models
              target: /smarteval/models
            - type: bind
              source: ./api/routers
              target: /smarteval/routers
        depends_on:
            - "mongo-db"
        command: ./wait-for-it.sh -t 0 mongo-db:27018 -- npm run dev
    
    smarteval-frontend:
        build: server-app/
        stdin_open: true
        tty: true
        working_dir: /smarteval
        ports:
            - 3000:3000
        volumes:
            - type: bind
              source: ./server-app/public
              target: /smarteval/public
            - type: bind
              source: ./server-app/src
              target: /smarteval/src
        command: npm run start

    mongo-db:
        build: db
        ports:
            - 27018:27018
        networks:
            - backend
        volumes:
            - db-data:/data/db-smarteval

networks:
    backend:

volumes:
    db-data:
